# Generated by Django 6.0.2 on 2026-02-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="USCity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("state", models.CharField(db_index=True, max_length=2)),
                ("state_name", models.CharField(max_length=50)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("population", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "us_cities",
                "ordering": ["city", "state"],
                "unique_together": {("city", "state")},
            },
        ),
    ]
