# Generated by Django 6.0.2 on 2026-02-27 01:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RideOffer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("estimated_arrival_minutes", models.PositiveIntegerField(default=0)),
                ("message", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ride_offers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ride_offers",
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="RideRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pickup_city", models.CharField(max_length=100)),
                ("pickup_state", models.CharField(max_length=2)),
                ("pickup_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("pickup_lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("dropoff_city", models.CharField(max_length=100)),
                ("dropoff_state", models.CharField(max_length=2)),
                ("dropoff_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("dropoff_lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("distance_miles", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "suggested_price",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "time_type",
                    models.CharField(
                        choices=[
                            ("immediate", "Right Now"),
                            ("specific", "Specific Time"),
                            ("range", "Time Range"),
                        ],
                        max_length=10,
                    ),
                ),
                ("requested_time", models.DateTimeField(blank=True, null=True)),
                ("time_range_start", models.DateTimeField(blank=True, null=True)),
                ("time_range_end", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("offered", "Offers Received"),
                            ("accepted", "Accepted"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accepted_offer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_for_request",
                        to="rides.rideoffer",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ride_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ride_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="rideoffer",
            name="ride_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="rides.riderequest",
            ),
        ),
        migrations.CreateModel(
            name="CompletedRide",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("final_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("distance_miles", models.DecimalField(decimal_places=2, max_digits=8)),
                ("pickup_time", models.DateTimeField(blank=True, null=True)),
                ("dropoff_time", models.DateTimeField(blank=True, null=True)),
                (
                    "driver_rating",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "rider_rating",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_drives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_rides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ride_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_ride",
                        to="rides.riderequest",
                    ),
                ),
            ],
            options={
                "db_table": "completed_rides",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="rideoffer",
            unique_together={("ride_request", "driver")},
        ),
    ]
